// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFi3uuCAV7sIU-Io9_wKY_cbwy6tNIQ7A',
    appId: '1:571806981577:web:898e9e1b321b767bce9c18',
    messagingSenderId: '571806981577',
    projectId: 'rating-app-flutter-46dc0',
    authDomain: 'rating-app-flutter-46dc0.firebaseapp.com',
    storageBucket: 'rating-app-flutter-46dc0.firebasestorage.app',
    measurementId: 'G-WZ28TE0QKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-263BvxDgsXa8csv4ag07r6Fky1WpKL0',
    appId: '1:571806981577:android:24b1f7a204b08627ce9c18',
    messagingSenderId: '571806981577',
    projectId: 'rating-app-flutter-46dc0',
    storageBucket: 'rating-app-flutter-46dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnMu7XUqPXT5jxdR-rh9G0fqqpOVMboAg',
    appId: '1:571806981577:ios:ace897aaf50f7f7ace9c18',
    messagingSenderId: '571806981577',
    projectId: 'rating-app-flutter-46dc0',
    storageBucket: 'rating-app-flutter-46dc0.firebasestorage.app',
    iosBundleId: 'com.example.ratingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnMu7XUqPXT5jxdR-rh9G0fqqpOVMboAg',
    appId: '1:571806981577:ios:ace897aaf50f7f7ace9c18',
    messagingSenderId: '571806981577',
    projectId: 'rating-app-flutter-46dc0',
    storageBucket: 'rating-app-flutter-46dc0.firebasestorage.app',
    iosBundleId: 'com.example.ratingApp',
  );

}